# Generated by Django 6.0.1 on 2026-02-07 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='product_image'),
        ),
    ]
